name: tv_screensaver_app
description: A basic screensaver app for Android TV with 4K support.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.4.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  palette_generator: ^0.3.3
  lottie: ^3.3.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/rain.json
    - assets/lottie/cloudy.json
    - assets/lottie/windy.json
    - assets/lottie/sunny.json
    - assets/lottie/hot.json
    - assets/lottie/storm.json
    - assets/lottie/night.json
