name: tv_screensaver_app
description: A basic screensaver app for Android TV with 4K support.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - .env
